import type { Metadata } from "next";
import "./globals.css";
import "antd/dist/reset.css";
import Header from "@/components/Header";
import axios from "axios";
import Footer from "@/components/Footer";

type Category = {
  id: string;
  title: string;
  slug: string;
  parent?: { id: string; slug: string; title: string } | string;
};

const apiUrl = process.env.NEXT_PUBLIC_API_URL || "http://localhost:3000";

async function fetchCategories(): Promise<Category[]> {
  try {
    const res = await axios.get(`${apiUrl}/api/categories?depth=2&limit=50`);
    const categories = res.data.docs || [];
    console.log("Fetched categories for layout:", categories);
    return categories;
  } catch (err) {
    if (
      err &&
      typeof err === "object" &&
      "response" in err &&
      err.response &&
      typeof err.response === "object" &&
      "data" in err.response
    ) {
      console.error("Error fetching categories for layout:", err.response.data);
    } else if (err instanceof Error) {
      console.error("Error fetching categories for layout:", err.message);
    } else {
      console.error("Error fetching categories for layout:", err);
    }
    return [];
  }
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const categories = await fetchCategories();

  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <Header categories={categories} />
        {children}
        <Footer />
      </body>
    </html>
  );
}